### PR TITLE
Remove support for Elasticsearch requirement

### PR DESCRIPTION
**Pull request by ruflin**
So far I have not seen a package that would need to specify requirements for an Elasticsearch version as the Elasticsearch and Kibana version are tied together in the minor. Because of this removing support for Elasticsearch requirements for now. We can readd it later if we need.

This also cleans up the existing packages to remove the mention of Elasticsearch and some other examples that were still around.

As a follow up, integrations packages should be updated to get rid of the requirement. But more changes will happen to the requirements after https://github.com/elastic/package-registry/pull/515 is merged so perhaps we rather wait with this a bit more.

This change should not break any existing packages.

### CODE REVIEW

**Comment by ruflin** [comment]
@jonathan-buttner This will probably also need an update to the Endpoint package.

**Comment by mtojek** [comment]
I think you should rollout this the other way round. First, make sure nobody uses/publishes the field, then remove it.

What about existing packages? I think @jonathan-buttner raised a similar issue a day ago (backwards incompatible change).

**Comment by ruflin** [comment]
As the field has not effects I would consider this "nobody is using it" ;-) As it doesn't break any existing packages, I think it is fine to get this in first.

For the existing packages already released, I would not touch them as additional data can be there but will not be used.

**Comment by mtojek** [comment]
> As the field has not effects I would consider this "nobody is using it" ;-) As it doesn't break any existing packages, I think it is fine to get this in first.

Usage:
https://github.com/elastic/integrations/blob/master/dev/import-beats/requirement.go#L30

> For the existing packages already released, I would not touch them as additional data can be there but will not be used.

I agree with this approach :)

**Comment by ruflin** [comment]
@mtojek Will you take care of the integrations usage or should I open a PR there?

**Comment by mtojek** [comment]
> @mtojek Will you take care of the integrations usage or should I open a PR there?

Sure, I can help here.

**Comment by ruflin** [comment]
@mtojek Thanks

**Comment by jonathan-buttner** [comment]
> @jonathan-buttner This will probably also need an update to the Endpoint package.

Thanks! I'll make sure our repo is updated 👍

**Comment by ruflin** [comment]
@mtojek as https://github.com/elastic/integrations/pull/92 is merged, ok to get this one in?

**Pull request merged**
