### PR TITLE
Add flag to enable profiling with HTTP pprof

### PR DESCRIPTION
**Pull request by jsoriano**
Add flag to enable profiling with HTTP pprof.

### CODE REVIEW

**Comment by ruflin** [comment]
Should we enable it by default but only expose it on localhost? This has the advantage that also in prod you can exec into the container and check potential issues.

**Comment by jsoriano** [comment]
> Should we enable it by default but only expose it on localhost? This has the advantage that also in prod you can exec into the container and check potential issues.

@ruflin I don't have a strong opinion, in general pprof uses to be optional in Go applications that support it, but I don't see a special problem on starting it by default, apart or opening an additional port, even if it is only locally. An alternative could be to don't enable it by default, but add the flag in the Docker images, where opening additional ports is surely not going to cause conflicts.

I have added it as default, as well as some docs. Error starting the server for http prof is handled now, so it explicitly fails if it cannot be opened, I think this is important to avoid cases where one ends-up profiling the wrong process :)

Let me know what you think.

**Review by mtojek — APPROVED** [review]
I think it's safe unless we expose it on public port, which I see it isn't the case here.

**Comment by ruflin** [comment]
Already merged but will still comment. If run outside the docker container, it might cause some conflicts with other go httpprof (agent?) on the same port. An alternative would have been to only enabled it by default if run inside the container (container passes the flag) but if run directly as binary it is not exposed by default. But that might also be surprising to have 2 different behaviours. One more option is just to enable it for us for the prod environments that are running.

**Comment by jsoriano** [comment]
> Already merged but will still comment. If run outside the docker container, it might cause some conflicts with other go httpprof (agent?) on the same port. An alternative would have been to only enabled it by default if run inside the container (container passes the flag) but if run directly as binary it is not exposed by default. But that might also be surprising to have 2 different behaviours. One more option is just to enable it for us for the prod environments that are running.

Yes, these were exactly my original thoughts when I didn't enable it by default :slightly_smiling_face: I agree that enabling it only when used is cleaner, I will open a PR to go back to this, and will take this into account for the production deployment.

**Comment by jsoriano** [comment]
https://github.com/elastic/package-registry/pull/710

**Pull request merged**
