### PR TITLE
Fill deprecated license field with the value of the new subscription condition

### PR DESCRIPTION
**Pull request by jsoriano**
Alternative to https://github.com/elastic/package-registry/pull/825, that only adds a compatibility layer from the old to the new field.

### CODE REVIEW

**Review by mtojek — COMMENTED** [review]
It seems that you have to update golden files.

**Review by mtojek — COMMENTED** [review]
As the next step, you can adjust the `elastic-package create` to handle it correctly.

BTW Does it need a changelog entry?

**Comment by jsoriano** [comment]
Changelog added.

**Review by mtojek — APPROVED** [review]

**Pull request merged**
