### PR TITLE
Add traces as valid type

### PR DESCRIPTION
**Pull request by jalvz**
Follow up on https://github.com/elastic/package-spec/pull/78

### CODE REVIEW

**Review by ruflin — COMMENTED** [review]
Change LGTM, could you add a changelog entry?

Would be good if @ycombinator or @mtojek could also have a look.

**Review by mtojek — COMMENTED** [review]
Could you please add a new test package with relevant data stream to the `testdata/package` directory? You can test it with `go test .`. You will also need to regenerate expected data with `go test . -generate`.

**Comment by mtojek** [comment]
As @ruflin has already mentioned, please add a CHANGELOG.

**Review by mtojek — APPROVED** [review]
Free free to merge it if the CI build goes green.

**Pull request merged**
