### PR TITLE
OpenAPI specs

### PR DESCRIPTION
**Pull request by ruflin**
This PR is to kick of an OpenAPI spec for the package-registry to document the API endpoints. For now it is kept simple.

This comes out of https://github.com/elastic/package-registry/issues/487#issuecomment-637828773

### CODE REVIEW

**Comment by jfsiii** [comment]
@ruflin can we commit this partial implementation and keep improving it or is there some other criteria for merging this?

**Comment by ruflin** [comment]
@jfsiii Yes, I will try to review / update again and get it in.

**Comment by ruflin** [comment]
@jfsiii I just made this ready for review. Some specs are missing but the ones we have should be correct. Lets have a first version in and intereated on it.

**Comment by ruflin** [comment]
@jfsiii Would be great if you could open a PR. The part I worried about adding this now was that we are still changing some bits (hopefully stopping end of this week) and wanted 1 less movable part.

**Comment by jfsiii** [comment]
@ruflin sure thing, I'll send one soon

**Pull request merged**
