### PR TITLE
Do not compress archived data

### PR DESCRIPTION
**Pull request by mtojek**
This PR disables compressing on-the-fly for archived data. Even though the heaviest method on the request path is `LoadAssets()`, it will speed up processing.

### CODE REVIEW

**Comment by mtojek** [comment]
There was a general idea (mostly for Kibana) for performance improvement focused on shortening total time of package installation and Kibana's boot up. As the size of resources is not huge, we can disable the compression and simply serve the content.

**Comment by ruflin** [comment]
So the problem is that when it is compress, it needs more CPU resources on the Kibana side to decompress?

**Comment by mtojek** [comment]
When it compresses it can stream the archive slower...

**Comment by mtojek** [comment]
Decided to put this one on hold until it's a real problem.

**Pull request closed without merging**
