### PR TITLE
Remove `removable` flag from package manifest

### PR DESCRIPTION
**Pull request by ruflin**
Based on the discussion in https://github.com/elastic/package-registry/issues/455 it is not up to the package to decide which packages can be removed but Kibana. Because of this, the removable flag is removed from the registry and the packages.

Closing https://github.com/elastic/package-registry/issues/455

### CODE REVIEW

**Comment by ruflin** [comment]
This PR should only be merged if changes made it into Kibana. @paul-tavares Could you ping us here when this happened?

**Comment by mtojek** [comment]
Did you check if the flag is used in the integrations repository?

**Comment by ruflin** [comment]
@mtojek It is for the system package. Al others are set to true (the default): https://github.com/elastic/integrations/blob/0ae2f28fa667952f1b8c682ebec4163bbfe3bef6/dev/import-beats/packages.go#L26 I'll follow up on the integrations repo as soon as we get this in, but first work must happen in Kibana.

**Comment by jfsiii** [comment]
https://github.com/elastic/kibana/pull/69761 is ready but without https://github.com/elastic/package-registry/issues/204 & the corresponding Kibana change we can't push changes independently

**Comment by ruflin** [comment]
@jfsiii Not sure I follow why https://github.com/elastic/kibana/pull/69761 can't be merged as it only removes a field and I assume if the registry still ships it, it should not affect the Kibana?

If we would use the versioned API for every breaking change we do at the moment, we would already be at v25. This will of course change when we hit 7.9.

**Comment by jfsiii** [comment]
@ruflin You're right https://github.com/elastic/kibana/pull/69761 can go in before this change, just not the other way around. I'll merge that PR now

> If we would use the versioned API for every breaking change we do at the moment, we would already be at v25.

Having _a_ strategy doesn't mean we need to use _that_ strategy but we can discuss that in the relevant issue

**Comment by ruflin** [comment]
@jfsiii I kicked off https://github.com/elastic/package-registry/pull/560 related to the above.

**Comment by ruflin** [comment]
Merging as https://github.com/elastic/kibana/pull/69906 is merged.

**Pull request merged**
