### PR TITLE
Update package output structure

### PR DESCRIPTION
**Pull request by ruflin**
This change contains several changes to the output generated for the package API endpoint:

* dataset.id is renamed to dataset.name
* datasources is renamed to config_templates. Currently only in the output, packages can follow later.
* config_templates (aka datasources) do not pregenerate the content anymore to simply config building in Kibana
* template_content is removed

Further change is done to use `Dataset(s)` instead of `DataSet(s)` in the code for consistency.

### CODE REVIEW

**Comment by ruflin** [comment]
@jen-huang This is related to Phase 3: https://github.com/elastic/beats/issues/19082 You should be able to use this branch to test changes in Kibana.

**Comment by ruflin** [comment]
Part of https://github.com/elastic/package-registry/issues/517

**Comment by jen-huang** [comment]
I'm hitting errors with `mage build` using this branch now. There are some conflicts with master if I try to merge. Can you try?

**Comment by ruflin** [comment]
@jen-huang I rebased on master, now things should work as expected.

**Pull request merged**
