### PR TITLE
Add package name to dataset

### PR DESCRIPTION
**Pull request by ruflin**
The package name in the dataset is useful in EPM. For this reason it is added here.

### CODE REVIEW

**Comment by ruflin** [comment]
@jfsiii I have the suspicion that later on `package.version` will also become useful, not only the name. For now I only added the name, but later we could convert it to:

```
{ 
  "package": {
    "name": "foo",
    "version": "1.2.3"
  }
}
```

**Comment by ruflin** [comment]
@jfsiii Could you help me to get the necessary changes ready on the EPM side if you are good with the change?

**Comment by jfsiii** [comment]
@ruflin sure thing. Sorry for the lag. Thanks for the ping.

We already have [`Dataset.package`](https://github.com/elastic/kibana/blob/c154afc02b181daf9f0337edb4a2a5b8a79744cd/x-pack/legacy/plugins/epm/common/types.ts#L133) so I think the only work is removing the code that manually inserts it. I'll post a PR soon.

**Comment by ruflin** [comment]
Merged. Will redeploy after the demo today ;-)

**Comment by jfsiii** [comment]
I just remembered that @neptunian has a PR that changes this to `packageName`. https://github.com/elastic/kibana/pull/54037

So that should either be reverted to `package` or the registry should use `packageName` so there's agreement

**Comment by ruflin** [comment]
Good point, lets stick to `package` for now if @neptunian is ok with it.

**Pull request merged**
