### PR TITLE
Delete package index.json

### PR DESCRIPTION
**Pull request by mtojek**
Delete package `index.json` from archive and do not serve it on endpoint (not used by Kibana).

### CODE REVIEW

**Comment by mtojek** [comment]
I'm confused now. The `index.json` is still accessible on `/` and Kibana doesn't use the one in the archive. Could you please provide detailed overview on why this should stay as is?

**Comment by ruflin** [comment]
I misread the code and I thought it also removes the one from the service and `/` is not possible anymore. My bad.

About removing it from the package: Did you try building a config and save it in Kibana? I'm curious if it still works.

**Comment by jfsiii** [comment]
I ran the registry locally with

```
docker pull docker.elastic.co/package-registry/package-registry:PR-488
docker run -p 8080:8080  $(docker image ls docker.elastic.co/package-registry/package-registry:PR-488 -q)
```

and ES with (needs gold+ to set the registry)

```
yarn es snapshot --license=trial  -E xpack.security.authc.api_key.enabled=true
```

and Kibana with

```
 yarn start --no-base-path --xpack.ingestManager.enabled=true --xpack.ingestManager.epm.registryUrl=http://localhost:8080
```

then added a Data Source for nginx and everything looked good
Screen Shot 2020-06-02 at 7 34 27 AM

**Comment by mtojek** [comment]
I confirm that it works too, but accidentally found a side issue in Kibana: https://github.com/elastic/kibana/issues/67938

**Comment by nchaulet** [comment]
I am curious here if deleting index.json is not the wrong solution, should we not use it in the packageIndexHandler instead?

**Comment by mtojek** [comment]
We're adjusting the solution to not require `mage build` at all, hence the `index.json` is created dynamically. Keep in mind that in the future we'll have 100000.. of revisions, so we might face scaling problems storing all of these.

**Comment by ruflin** [comment]
@nchaulet Mid and long term users will be able to build packages in Kibana and upload them manually to Kibana. For these packages, the index.json is missing. This change makes sure, they are not used "accidentially" by the Ingest Manager when not accessing the registry directly.

**Pull request merged**
